# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c09666ae03bb81b7c5bfc4a22eb05f81299db02a5c58345a1744e7480eebd7c3975d783dd7c592bb7061f2e976bda6d32240f1e4685aa2f4479260768799c024

test:
  secret_key_base: b9c5b4772251d4d8198e049f576fc540d83f90a9e78ae861bd35751ec83a6167521686ae2fc4bb2c92a81e3dfe82942b44a93ec4f9d3b3571c7a185ee3429ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
